import os
import uuid
import zipfile
import io
import json
import sqlite3
from datetime import datetime, timezone, timedelta
from PIL import Image, ImageOps
from flask import Flask, render_template, request, redirect, url_for, flash, abort, jsonify, send_from_directory, send_file, make_response
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import or_, and_
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from itsdangerous import URLSafeTimedSerializer as Serializer
import google.generativeai as genai
from flask_mail import Mail, Message

# --- IMPORT KLUCZY ---
try:
    import sekrety
    GEMINI_KEY = sekrety.GEMINI_KEY
    MAIL_PWD = sekrety.MAIL_PWD
    SECRET_KEY_APP = getattr(sekrety, 'SECRET_KEY', 'super_tajny_klucz_gieldy')
except ImportError:
    GEMINI_KEY = None
    MAIL_PWD = None
    SECRET_KEY_APP = 'dev_key_2024'

app = Flask(__name__)
app.secret_key = SECRET_KEY_APP

# --- KONFIGURACJA ---
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///gielda.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
UPLOAD_FOLDER = 'static/uploads'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif', 'webp'}
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

if not os.path.exists(UPLOAD_FOLDER):
    os.makedirs(UPLOAD_FOLDER)

db = SQLAlchemy(app)
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'login'

# --- ŚLEDZENIE AKTYWNOŚCI (ONLINE) ---
@app.before_request
def update_last_seen():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()


# --- TŁUMACZENIA (SŁOWNIK PEŁNY) ---
TRANSLATIONS = {
    'pl': {
        'search_ph': 'Wpisz np. Audi A4, Automat...', 'btn_search': 'SZUKAJ', 'filters': 'Filtry', 
        'cat': 'Kategoria', 'fuel': 'Paliwo', 'gear': 'Skrzynia', 'year': 'Rok od', 'price': 'Cena do', 'mileage': 'Przebieg do', 
        'add': 'DODAJ OGŁOSZENIE', 'login': 'Logowanie', 'logout': 'Wyloguj', 'account': 'Konto',
        'hero_h1': 'Znajdź auto w Radomiu', 'hero_p': 'Lokalny rynek. Weryfikacja AI. Tradycja i Nowoczesność.', 
        'all': 'Wszystkie', 'man': 'Manualna', 'auto': 'Automatyczna', 'available': 'Dostępne Oferty', 'found': 'Znaleziono',
        'garage': 'Twój Garaż', 'limit': 'Limit Zapytań AI', 'days_left': 'dni', 'expired': 'WYGASŁO',
        'scan_cam': 'SKANUJ (APARAT)', 'scan_file': 'WGRAJ (PLIK)', 'desc_ai': 'Opis Generowany przez Eksperta AI',
        'safety': 'Bezpieczny Zakup', 'check_vin': 'Sprawdź VIN', 'calc_ins': 'Oblicz OC/AC',
        'show_phone': 'Pokaż Numer', 'send_msg': 'Napisz Wiadomość', 'watch': 'Obserwuj', 'watching': 'Obserwujesz'
    },
    'en': {
        'search_ph': 'E.g. Audi A4, Automatic...', 'btn_search': 'SEARCH', 'filters': 'Filters', 
        'cat': 'Category', 'fuel': 'Fuel', 'gear': 'Transmission', 'year': 'Year from', 'price': 'Price to', 'mileage': 'Mileage to', 
        'add': 'ADD LISTING', 'login': 'Login', 'logout': 'Logout', 'account': 'Account',
        'hero_h1': 'Find a car in Radom', 'hero_p': 'Local market. AI Verified. Tradition meets Modernity.', 
        'all': 'All', 'man': 'Manual', 'auto': 'Automatic', 'available': 'Available Offers', 'found': 'Found',
        'garage': 'Your Garage', 'limit': 'AI Limit', 'days_left': 'days left', 'expired': 'EXPIRED',
        'scan_cam': 'SCAN (CAMERA)', 'scan_file': 'UPLOAD (FILE)', 'desc_ai': 'Description Generated by AI Expert',
        'safety': 'Safe Purchase', 'check_vin': 'Check VIN', 'calc_ins': 'Calculate Insurance',
        'show_phone': 'Show Number', 'send_msg': 'Send Message', 'watch': 'Watch', 'watching': 'Watching'
    },
    'de': {
        'search_ph': 'Z.B. Audi A4, Automatik...', 'btn_search': 'SUCHEN', 'filters': 'Filter', 
        'cat': 'Kategorie', 'fuel': 'Kraftstoff', 'gear': 'Getriebe', 'year': 'Baujahr ab', 'price': 'Preis bis', 'mileage': 'KM bis', 
        'add': 'ANZEIGE AUFGEBEN', 'login': 'Anmelden', 'logout': 'Abmelden', 'account': 'Konto',
        'hero_h1': 'Finde ein Auto in Radom', 'hero_p': 'Lokaler Markt. AI geprüft. Tradition und Moderne.', 
        'all': 'Alle', 'man': 'Schaltgetriebe', 'auto': 'Automatik', 'available': 'Verfügbare Angebote', 'found': 'Gefunden',
        'garage': 'Deine Garage', 'limit': 'AI Limit', 'days_left': 'Tage übrig', 'expired': 'ABGELAUFEN',
        'scan_cam': 'SCAN (KAMERA)', 'scan_file': 'HOCHLADEN (DATEI)', 'desc_ai': 'Beschreibung vom AI-Experten',
        'safety': 'Sicherer Kauf', 'check_vin': 'VIN prüfen', 'calc_ins': 'Versicherung',
        'show_phone': 'Nummer anzeigen', 'send_msg': 'Nachricht senden', 'watch': 'Merken', 'watching': 'Gemerkt'
    }
}

@app.context_processor
def inject_conf_var():
    lang = request.cookies.get('lang', 'pl')
    return dict(lang=lang, t=TRANSLATIONS.get(lang, TRANSLATIONS['pl']))

@app.route('/set_lang/<lang_code>')
def set_language(lang_code):
    if lang_code not in TRANSLATIONS: lang_code = 'pl'
    resp = make_response(redirect(request.referrer or '/'))
    resp.set_cookie('lang', lang_code, max_age=60*60*24*30)
    return resp

# --- AI CONFIG ---
if GEMINI_KEY:
    genai.configure(api_key=GEMINI_KEY)
    try: model_ai = genai.GenerativeModel('gemini-3-flash-preview')
    except: model_ai = None
else: model_ai = None

mail = Mail(app)

# --- BAZA DANYCH ---
class Favorite(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    car_id = db.Column(db.Integer, db.ForeignKey('car.id'), nullable=False)
    car = db.relationship('Car', backref='fav_entries')

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(200), nullable=False)
    lokalizacja = db.Column(db.String(100), default='Radom')
    ai_requests_today = db.Column(db.Integer, default=0)
    last_ai_request_date = db.Column(db.Date, default=datetime.utcnow().date())
    last_seen = db.Column(db.DateTime, default=datetime.utcnow)
    cars = db.relationship('Car', backref='owner', lazy=True, cascade="all, delete-orphan")
    favorites = db.relationship('Favorite', backref='user', lazy=True, cascade="all, delete-orphan")
    def get_reset_token(self): return Serializer(app.config['SECRET_KEY']).dumps({'user_id': self.id})
    @staticmethod
    def verify_reset_token(token):
        try: return User.query.get(Serializer(app.config['SECRET_KEY']).loads(token)['user_id'])
        except: return None

class Car(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    typ = db.Column(db.String(20), default='Osobowe')
    marka = db.Column(db.String(50), nullable=False)
    model = db.Column(db.String(50), nullable=False)
    rok = db.Column(db.Integer, nullable=False)
    cena = db.Column(db.Float, nullable=False)
    opis = db.Column(db.Text, nullable=False)
    telefon = db.Column(db.String(20), nullable=False)
    img = db.Column(db.String(200), nullable=False)
    zrodlo = db.Column(db.String(50), default='Radom')
    latitude = db.Column(db.Float, nullable=True)
    longitude = db.Column(db.Float, nullable=True)
    is_promoted = db.Column(db.Boolean, default=False)
    ai_label = db.Column(db.String(500), nullable=True)
    ai_valuation_data = db.Column(db.String(50), nullable=True)
    skrzynia = db.Column(db.String(20))
    paliwo = db.Column(db.String(20))
    nadwozie = db.Column(db.String(30))
    pojemnosc = db.Column(db.String(20))
    przebieg = db.Column(db.Integer, default=0)
    wyswietlenia = db.Column(db.Integer, default=0)
    views = db.Column(db.Integer, default=0)
    data_dodania = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    images = db.relationship('CarImage', backref='car', lazy=True, cascade="all, delete-orphan")

class CarImage(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    image_path = db.Column(db.String(200), nullable=False)
    car_id = db.Column(db.Integer, db.ForeignKey('car.id'), nullable=False)

@login_manager.user_loader
def load_user(user_id): return User.query.get(int(user_id))

# --- LOGIKA ---
def check_ai_limit():
    if not current_user.is_authenticated: return False
    today = datetime.utcnow().date()
    if current_user.last_ai_request_date != today:
        current_user.ai_requests_today = 0
        current_user.last_ai_request_date = today
        db.session.commit()
    return current_user.ai_requests_today < 1000

def save_optimized_image(file):
    filename = f"{uuid.uuid4().hex}.webp"
    filepath = os.path.join(app.config['UPLOAD_FOLDER'], filename)
    img = Image.open(file)
    try: img = ImageOps.exif_transpose(img) # NAPRAWA ROTACJI
    except: pass 
    if img.mode in ("RGBA", "P"): img = img.convert("RGB")
    if img.width > 1200:
        w_percent = (1200 / float(img.width))
        h_size = int((float(img.height) * float(w_percent)))
        img = img.resize((1200, h_size), Image.Resampling.LANCZOS) # KOMPRESJA
    img.save(filepath, "WEBP", quality=80)
    return filename

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

def update_market_valuation(car):
    if not model_ai: return
    try:
        # EKSPERCKA ANALIZA
        prompt = f"""
        Jesteś ekspertem rynku motoryzacyjnego. Analiza pojazdu: {car.marka} {car.model}, {car.rok}, {car.cena} PLN.
        Zwróć TYLKO JSON: 
        {{
            "score": 85, 
            "label": "SUPER CENA", 
            "color": "success", 
            "sample_size": "28 ofert w regionie", 
            "market_info": "Cena o 10% niższa niż średnia rynkowa dla tego rocznika."
        }}
        """
        response = model_ai.generate_content(prompt)
        clean_json = response.text.replace('```json', '').replace('```', '').strip()
        json.loads(clean_json)
        car.ai_label = clean_json
        car.ai_valuation_data = datetime.now().strftime("%Y-%m-%d")
        db.session.commit()
    except Exception as e: print(f"AI Error: {e}")

@app.template_filter('from_json')
def from_json_filter(value):
    try: return json.loads(value)
    except: return None

# --- TRASY ---
@app.route('/')
def index():
    q = request.args.get('q', '').strip()
    query = Car.query
    if q:
        terms = q.split()
        conditions = []
        for term in terms:
            conditions.append(or_(Car.marka.icontains(term), Car.model.icontains(term), Car.paliwo.icontains(term), Car.typ.icontains(term), Car.rok.cast(db.String).icontains(term)))
        query = query.filter(and_(*conditions))
    
    # PEŁNE FILTRY
    cat = request.args.get('typ', '')
    if cat: query = query.filter(Car.typ == cat)
    paliwo = request.args.get('paliwo', '')
    if paliwo: query = query.filter(Car.paliwo == paliwo)
    skrzynia = request.args.get('skrzynia', '')
    if skrzynia: query = query.filter(Car.skrzynia == skrzynia)
    max_cena = request.args.get('max_cena', type=float)
    if max_cena: query = query.filter(Car.cena <= max_cena)
    min_rok = request.args.get('min_rok', type=int)
    if min_rok: query = query.filter(Car.rok >= min_rok)
    max_przebieg = request.args.get('max_przebieg', type=int)
    if max_przebieg: query = query.filter(Car.przebieg <= max_przebieg)

    cars = query.order_by(Car.is_promoted.desc(), Car.data_dodania.desc()).all()
    return render_template('index.html', cars=cars, now=datetime.utcnow())

@app.route('/ogloszenie/<int:car_id>')
def car_details(car_id):
    car = Car.query.get_or_404(car_id)
    if car.views is None: car.views = 0
    car.views += 1
    
    # 7 DNI UPDATE
    should_update = False
    if not car.ai_valuation_data or not car.ai_label: should_update = True
    else:
        try:
            last_check = datetime.strptime(car.ai_valuation_data, "%Y-%m-%d")
            if (datetime.now() - last_check).days >= 7: should_update = True
        except: should_update = True   
    if should_update and model_ai:
        try: update_market_valuation(car)
        except: pass
    db.session.commit()
    return render_template('details.html', car=car, now=datetime.utcnow())

@app.route('/profil')
@login_required
def profil():
    user_count = 0; online_count = 0; total_views = 0
    
    if current_user.username == 'admin' or current_user.id == 1:
        cars = Car.query.order_by(Car.data_dodania.desc()).all()
        # STATYSTYKI DLA ADMINA
        user_count = User.query.count()
        # Użytkownicy aktywni w ostatnich 5 minutach
        active_since = datetime.utcnow() - timedelta(minutes=5)
        online_count = User.query.filter(User.last_seen >= active_since).count()
        total_views = db.session.query(db.func.sum(Car.views)).scalar() or 0
    else:
        cars = Car.query.filter_by(user_id=current_user.id).order_by(Car.data_dodania.desc()).all()
        
    favorites = Favorite.query.filter_by(user_id=current_user.id).all()
    return render_template('profil.html', cars=cars, favorites=favorites, now=datetime.utcnow(), user_count=user_count, online_count=online_count, total_views=total_views)


@app.route('/dodaj', methods=['POST'])
@login_required
def dodaj_ogloszenie():
    files = request.files.getlist('zdjecia')
    saved_paths = []
    # SKANER
    if 'scan_image' in request.files and request.files['scan_image'].filename != '':
        f = request.files['scan_image']
        if allowed_file(f.filename): saved_paths.append(url_for('static', filename='uploads/' + save_optimized_image(f)))
    # GALERIA
    for file in files[:15]:
        if file and allowed_file(file.filename): saved_paths.append(url_for('static', filename='uploads/' + save_optimized_image(file)))
    main_img = saved_paths[0] if saved_paths else 'https://placehold.co/600x400?text=Brak+Zdjecia'
    
    try: lat = float(request.form.get('lat')) 
    except: lat = None
    try: lon = float(request.form.get('lon')) 
    except: lon = None

    new_car = Car(
        marka=request.form.get('marka'), model=request.form.get('model'),
        rok=int(request.form.get('rok') or 0), cena=float(request.form.get('cena') or 0),
        typ=request.form.get('typ', 'Osobowe'), opis=request.form.get('opis', ''),
        telefon=request.form.get('telefon'), skrzynia=request.form.get('skrzynia'),
        paliwo=request.form.get('paliwo'), nadwozie=request.form.get('nadwozie'),
        pojemnosc=request.form.get('pojemnosc'), przebieg=int(request.form.get('przebieg') or 0),
        img=main_img, zrodlo=current_user.lokalizacja, user_id=current_user.id,
        latitude=lat, longitude=lon, data_dodania=datetime.utcnow()
    )
    db.session.add(new_car)
    db.session.flush()
    for p in saved_paths: db.session.add(CarImage(image_path=p, car_id=new_car.id))
    db.session.commit()
    flash('Dodano!', 'success')
    return redirect(url_for('profil'))

@app.route('/api/analyze-car', methods=['POST'])
@login_required
def api_analyze_car():
    if not model_ai: return jsonify({"error": "AI unavailable"}), 500
    if not check_ai_limit(): return jsonify({"error": "Limit"}), 429
    file = request.files.get('scan_image')
    if not file: return jsonify({"error": "Brak pliku"}), 400
    try:
        # PROMPT EKSPERCKI (OPIS + DANE)
        prompt = """
        Przeanalizuj zdjęcie pojazdu.
        Zwróć JSON:
        {
            "kategoria": "Osobowe" lub "SUV" lub "Rower",
            "marka": "String",
            "model": "String",
            "rok_sugestia": 2020,
            "paliwo_sugestia": "Benzyna",
            "typ_nadwozia": "Sedan",
            "kolor": "Czarny",
            "opis_wizualny": "Napisz profesjonalny, marketingowy opis tego auta dla kupującego. Podkreśl widoczne cechy (np. alufelgi, stan lakieru, światła LED)."
        }
        """
        resp = model_ai.generate_content([prompt, {"mime_type": file.mimetype, "data": file.read()}])
        current_user.ai_requests_today += 1
        db.session.commit()
        return jsonify(json.loads(resp.text.replace('```json','').replace('```','').strip()))
    except: return jsonify({"error": "Błąd analizy"}), 500

@app.route('/api/generuj-opis', methods=['POST'])
@login_required
def generuj_opis_ai():
    if not model_ai: return jsonify({"opis": "Błąd AI"}), 500
    if not check_ai_limit(): return jsonify({"opis": "Limit wyczerpany"}), 429
    data = request.json
    try:
        prompt = f"Opisz przedmiot: {data}. Styl: zachęcający, profesjonalny handlarz."
        resp = model_ai.generate_content(prompt)
        current_user.ai_requests_today += 1
        db.session.commit()
        return jsonify({"opis": resp.text.strip()})
    except: return jsonify({"opis": "Błąd generowania"}), 500

@app.route('/usun/<int:car_id>', methods=['POST'])
@login_required
def delete_car(car_id):
    c = Car.query.get(car_id)
    if c and (c.user_id == current_user.id or current_user.username=='admin'):
        db.session.delete(c); db.session.commit()
    return redirect('/profil')

@app.route('/odswiez/<int:car_id>', methods=['POST'])
@login_required
def refresh_car(car_id):
    c = Car.query.get(car_id)
    if c and (c.user_id == current_user.id or current_user.username=='admin'):
        c.data_dodania = datetime.utcnow()
        db.session.commit()
    return redirect('/profil')

@app.route('/toggle_favorite/<int:car_id>')
@login_required
def toggle_favorite(car_id):
    fav = Favorite.query.filter_by(user_id=current_user.id, car_id=car_id).first()
    if fav: db.session.delete(fav)
    else: db.session.add(Favorite(user_id=current_user.id, car_id=car_id))
    db.session.commit()
    return redirect(request.referrer)

# --- SEO ROUTES ---
@app.route('/sitemap.xml')
def sitemap():
    base = request.url_root.rstrip('/')
    xml = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    for p in ['', 'login', 'register', 'kontakt', 'regulamin']:
        xml += f'<url><loc>{base}/{p}</loc><changefreq>weekly</changefreq></url>\n'
    for car in Car.query.order_by(Car.data_dodania.desc()).all():
        xml += f'<url><loc>{base}/ogloszenie/{car.id}</loc><changefreq>daily</changefreq></url>\n'
    xml += '</urlset>'
    return make_response(xml, 200, {'Content-Type': 'application/xml'})

@app.route('/robots.txt')
def robots():
    txt = f"User-agent: *\nAllow: /\nSitemap: {request.url_root.rstrip('/')}/sitemap.xml"
    return make_response(txt, 200, {'Content-Type': 'text/plain'})

# --- AUTH & OTHER ROUTES ---
@app.route('/login', methods=['GET','POST'])
def login():
    if request.method=='POST':
        u = User.query.filter_by(username=request.form['username']).first()
        if u and check_password_hash(u.password_hash, request.form['password']):
            login_user(u); return redirect(url_for('profil'))
    return render_template('login.html')

@app.route('/register', methods=['GET','POST'])
def register():
    if request.method=='POST':
        db.session.add(User(username=request.form['username'], email=request.form['email'], password_hash=generate_password_hash(request.form['password'])))
        db.session.commit(); return redirect(url_for('login'))
    return render_template('register.html')

@app.route('/logout')
def logout(): logout_user(); return redirect('/')

@app.route('/kontakt')
def kontakt(): return render_template('kontakt.html')
@app.route('/regulamin')
def regulamin(): return render_template('regulamin.html')
@app.route('/polityka')
def polityka(): return render_template('polityka.html')
@app.route("/reset_password", methods=['GET', 'POST'])
def reset_request(): return render_template('reset_request.html')
@app.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token): return render_template('reset_token.html')

@app.route('/edytuj/<int:id>', methods=['GET','POST'])
@login_required
def edytuj(id):
    car = Car.query.get_or_404(id)
    
    # Zabezpieczenie: tylko właściciel lub admin
    if car.user_id != current_user.id and current_user.username != 'admin':
        flash('Brak uprawnień.', 'danger') 
        return redirect('/')
        
    if request.method == 'POST':
        try:
            # 1. Zapis danych tekstowych
            car.marka = request.form.get('marka')
            car.model = request.form.get('model')
            car.cena = float(request.form.get('cena') or 0)
            car.rok = int(request.form.get('rok') or 0)
            car.przebieg = int(request.form.get('przebieg') or 0)
            car.paliwo = request.form.get('paliwo')
            car.skrzynia = request.form.get('skrzynia')
            car.pojemnosc = request.form.get('pojemnosc')
            car.nadwozie = request.form.get('nadwozie')
            car.telefon = request.form.get('telefon')
            car.opis = request.form.get('opis')
            
            # 2. OBSŁUGA NOWYCH ZDJĘĆ (TEGO BRAKOWAŁO)
            files = request.files.getlist('zdjecia')
            for file in files:
                if file and allowed_file(file.filename):
                    # Używamy tej samej funkcji optymalizacji co przy dodawaniu
                    filename = save_optimized_image(file)
                    # Tworzymy ścieżkę URL
                    path = url_for('static', filename='uploads/' + filename)
                    # Dodajemy wpis do bazy
                    new_img = CarImage(image_path=path, car_id=car.id)
                    db.session.add(new_img)
            
            db.session.commit()
            flash('Zapisano zmiany i dodano zdjęcia!', 'success')
            return redirect('/profil')
            
        except Exception as e:
            print(f"Błąd edycji: {e}")
            flash('Wystąpił błąd podczas zapisu.', 'danger')
            
    return render_template('edytuj.html', car=car)



@app.route('/admin/backup-db')
@login_required
def backup_db():
    if current_user.username != 'admin': abort(403)
    return send_from_directory('instance', 'gielda.db', as_attachment=True)

@app.route('/admin/full-backup')
@login_required
def full_backup():
    if current_user.username != 'admin': abort(403)
    memory_file = io.BytesIO()
    with zipfile.ZipFile(memory_file, 'w', zipfile.ZIP_DEFLATED) as zf:
        if os.path.exists('instance/gielda.db'): zf.write('instance/gielda.db', 'gielda.db')
        for root, dirs, files in os.walk('static/uploads'):
            for file in files: zf.write(os.path.join(root, file), os.path.join('uploads', file))
    memory_file.seek(0)
    return send_file(memory_file, download_name='backup_full.zip', as_attachment=True)

@app.route('/usun_zdjecie/<int:image_id>', methods=['POST'])
@login_required
def usun_zdjecie(image_id):
    img = CarImage.query.get_or_404(image_id)
    db.session.delete(img)
    db.session.commit()
    return jsonify({'success': True})

def update_db():
    with app.app_context():
        # Poprawione połączenie, żeby zapisać zmiany (commit)
        conn = sqlite3.connect('instance/gielda.db')
        c = conn.cursor()
        
        # Stare kolumny
        try: c.execute("ALTER TABLE car ADD COLUMN latitude FLOAT")
        except: pass
        try: c.execute("ALTER TABLE car ADD COLUMN longitude FLOAT")
        except: pass
        
        # --- TO MUSI BYĆ TUTAJ, W ŚRODKU FUNKCJI ---
        try: c.execute("ALTER TABLE user ADD COLUMN last_seen TIMESTAMP")
        except: pass
        
        # Zatwierdzenie zmian w bazie
        conn.commit()
        conn.close()

if __name__ == '__main__':
    update_db()
    with app.app_context(): db.create_all()
    app.run(host='0.0.0.0', port=5000)

